remote_theme: "jekyll/minima@1e8a445"
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: "Unraveling Culinary Complexity: A Data-Driven Analysis of Recipe Complexity and User Satisfaction"
site.title: ""
site.description: ""